openapi: 3.0.3
info:
  title: Recruitment Manager Api - OpenAPI 3.0.3
  description: |-
    Recruitment Manager Api OpenAPI 3.0.3 specification.
  license:
    name: Proprietary Licensing
  version: 1.0.0
servers:
  - url: http://localhost:8080
tags:
  - name: users
    description: Everything about Users
  - name: jobs
    description: Everything about Job postings
paths:
  /users:
    post:
      summary: Add new user
      operationId: addUser
      tags:
        - users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: User added
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"

  /users/{email}:  # Changed from '/get-user/{email}' to match '/users'
    get:
      summary: Get user by email
      operationId: getUserByEmail  # Changed operationId for clarity
      tags:
        - users
      parameters:
        - name: email
          in: path
          required: true
          description: Email of the user to retrieve
          schema:
            type: string
      responses:
        '200':
          description: User retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        '404':
          description: User not found
  /jobs:
    get:
      summary: Get all job postings
      operationId: getAllJobs
      tags:
        - jobs
      responses:
        '200':
          description: List of job postings
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/JobDto'

components:
  schemas:
    UserRole:
      type: string
      enum:
        - recruiter
        - recruited
    User:
      type: object
      properties:
        id:
          type: number
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        password:
          type: string
        username:
          type: string
        userRole:
          $ref: '#/components/schemas/UserRole'
    LoginUserDto:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          format: password
      required:
        - email
        - password
    JobDto:
      type: object
      properties:
        id:
          type: number
        title:
          type: string
        description:
          type: string
        location:
          type: string
        salary:
          type: number